![PFA.png]()

# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

In [1]:
# import numpy
import numpy as np

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',
 '_globals',
 '_mat',
 '_pytesttester',
 'abs',
 'absolute',
 'absolute_import',
 'add',
 'add_docstring',
 'add_newdoc',
 'add_newdoc_ufunc',
 'alen',
 'all',
 'allclose',
 'alltrue',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'asmatrix',
 'asscalar',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_not',
 'bitwise_or',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool',
 'bool8',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'byte_bounds',
 'bytes0',
 'bytes_',
 'c_',
 'can_cast',
 'cast',
 'cbrt',
 'cdouble',
 'ceil',
 'cfloat',
 'char',
 'character',
 'chararray',
 'choose',
 'clip',
 'clongdouble',
 'clongfloat',
 'column_stack',
 'common_type',
 'compare_chararrays',
 'compat',
 'complex',
 'complex128',
 'complex256',
 'complex64',
 'complex_',
 'complexfloating',
 'compress',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumproduct',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'deprecate',
 'deprecate_with_doc',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'disp',
 'divide',
 'division',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'fabs',
 'fastCopyAndTranspose',
 'fft',
 'fill_diagonal',
 'find_common_type',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float',
 'float128',
 'float16',
 'float32',
 'float64',
 'float_',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'format_parser',
 'frexp',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'fv',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_array_wrap',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'geterrobj',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'infty',
 'inner',
 'insert',
 'int',
 'int0',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'int_asbuffer',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'ipmt',
 'irr',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issctype',
 'issubclass_',
 'issubdtype',
 'issubsctype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loads',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'long',
 'longcomplex',
 'longdouble',
 'longfloat',
 'longlong',
 'lookfor',
 'ma',
 'mafromtxt',
 'mask_indices',
 'mat',
 'math',
 'matmul',
 'matrix',
 'matrixlib',
 'max',
 'maximum',
 'maximum_sctype',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mirr',
 'mod',
 'modf',
 'moveaxis',
 'msort',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'nbytes',
 'ndarray',
 'ndenumerate',
 'ndfromtxt',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'nper',
 'npv',
 'numarray',
 'number',
 'obj2sctype',
 'object',
 'object0',
 'object_',
 'ogrid',
 'oldnumeric',
 'ones',
 'ones_like',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'pi',
 'piecewise',
 'place',
 'pmt',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'power',
 'ppmt',
 'print_function',
 'printoptions',
 'prod',
 'product',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'pv',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'rank',
 'rate',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'recfromcsv',
 'recfromtxt',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'round_',
 'row_stack',
 's_',
 'safe_eval',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctype2char',
 'sctypeDict',
 'sctypeNA',
 'sctypes',
 'searchsorted',
 'select',
 'set_numeric_ops',
 'set_printoptions',
 'set_string_function',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'seterrobj',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'singlecomplex',
 'sinh',
 'size',
 'sometrue',
 'sort',
 'sort_complex',
 'source',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str',
 'str0',
 'str_',
 'string_',
 'subtract',
 'sum',
 'swapaxes',
 'sys',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'tracemalloc_domain',
 'transpose',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typeDict',
 'typeNA',
 'typecodes',
 'typename',
 'ubyte',
 'ufunc',
 'uint',
 'uint0',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulonglong',
 'unicode',
 'unicode_',
 'union1d',
 'unique',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vectorize',
 'version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

**One Dimension Array**

In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print("a:",a)
print(type(a))
print("a.shape:",a.shape)
a[4]=10
print("a:",a)
print("a.size:",a.size)
print(a[4])

a: [1 2 3 4 5 6]
<class 'numpy.ndarray'>
a.shape: (6,)
a: [ 1  2  3  4 10  6]
a.size: 6
10

**Exercise 1:**

Create an array called marks with following numbers: 85,90,95,92,98 and perform the following operations.

a) Display all elements in an array

 b) Find  type of an array

 c) Find shape of an array 

 d) Change last mark into 96

 e) Print last item in an array

In [5]:
arr = [85,90,95,92,98]
marks = np.array(arr)

In [10]:
# a) Display all elements in an array

print(marks)

[85 90 95 92 98]

In [11]:
# b) Find type of an array

print(type(marks))

<class 'numpy.ndarray'>

In [9]:
# c) Find shape of an array

print(marks.shape)

(5,)

In [14]:
# d) Change last mark into 96

marks[-1] = 96

In [15]:
# e) Print last item in an array

print(marks)

[85 90 95 92 96]

In [ ]:
#TODO
marks = np.array( [85,90,95,92,98] )

print("Marks:",marks)
print(type(marks))
print(marks.shape)

marks[4] = 96

print(marks[4])

Marks: [85 90 95 92 98]
<class 'numpy.ndarray'>
(5,)
96

**Two Dimension Array**

In [ ]:
b=np.array([[1,2,3],[4,5,6],[10,20,30]])
print("b:",b)
print("b.shape:",b.shape)
print("b.size:",b.size)

b: [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
b.shape: (3, 3)
b.size: 9

**Exercise 2:**

Create a two dimension array with following numbers: [85,90] [95,92] [98,100] and perform the following operations.

a) Display all elements in an array

b) Find type of an array

c) Find shape of an array

d) Find size of an array

In [13]:
#TODO

arr = np.array([ [85,90] , [95,92] ,[98,100] ])

print(arr)

print(type(arr))

print(arr.shape)
print(arr.size)

[[ 85  90]
 [ 95  92]
 [ 98 100]]
<class 'numpy.ndarray'>
(3, 2)
6

**Access array elements by index**

In [14]:
import numpy as np

a=np.array([1,2,3])
b=np.array([10,20,30])

print(a[0])
print(a[1])
print(a[2])
print(b[2])
print(b)

1
2
3
30
[10 20 30]

In [15]:
a=np.array([1,2,3])  #[1,2,3]
b=np.array([10,20,30]) #[10,20,30]
c=np.array([a[0]-b[0],a[1]-b[1],a[2]-b[2]]) #c[0]=a[0]-b[0]

print(c)

[ -9 -18 -27]

**Exercise 3:**

Let a array is [1,2,3], b array is [1,1,1] and c array is [5,5,5]. Create an arrray d, which sum of a+b+c.


d[0]=a[0]+b[0]+c[0]+d[0]

In [19]:
#TODO

a = np.array([1,2,3])
b = np.array([1,1,1])
c = np.array([5,5,5])

d = np.array([a[0] + b[0] + c[0] , a[1] + b[1] + c[1] , a[2] + b[2] + c[2] ])

print(d)

[7 8 9]

# Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:]) # arr[:]
print(arr[1:5]) 
print(arr[1:])
print(arr[2:4])

[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5 6 7]
[3 4]

**Exercise 4:**

Create an array called age with the following numbers 21,23,45,64,12,5,78,34,12,27. 

Print the following numbers using slicing:

64,12,5

23,45,64,12,5,78

12,**27**

In [22]:
#TODO

arr = np.array([21,23,45,64,12,5,78,34,12,27])

print(arr[3:6])
print(arr[1:7])
print(arr[8:])

[64 12  5]
[23 45 64 12  5 78]
[12 27]

# Numpy Functions

Numpy also provides many functions to create arrays:

In [ ]:
# Create an array of all zeros
aa=np.zeros((2,2))
print(aa)

[[0. 0.]
 [0. 0.]]

**Exercise 5:**

Create the following nd array using np.zeros function.

aa: [[0. 0. 0. 0.]

 [0. 0. 0. 0.]

 [0. 0. 0. 0.]

 [0. 0. 0. 0.]]

In [23]:
#TODO

aa = np.zeros((4,4))

print(aa)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
# Create an array of all ones
bb=np.ones((4,4))
print(bb)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

**Exercise 6:**

Create the following nd array using np.ones function.

bb: [[1. 1. 1.]

 [1. 1. 1.]]

In [24]:
#TODO
bb = np.ones((2,3))

print(bb)

[[1. 1. 1.]
 [1. 1. 1.]]

In [28]:
# Create a constant array
cc=np.full((2,2), 5, dtype=np.int16)
print(cc)

[[5 5]
 [5 5]]

In [29]:
# Create a constant array
dd=np.full((4,3),6.2, dtype=np.int16)
print(dd)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]

**Exercise 7:**

Create the following nd array using np.full function.

cc: [[5 5 5 5 5]

 [5 5 5 5 5]

 [5 5 5 5 5]

 [5 5 5 5 5]]

In [33]:
#TODO

cc = np.full((4,5),5.5, dtype=np.int16)
print(cc )

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]

In [34]:
# Create an array filled with random values
ee = np.random.random((3,3))
print(ee)

[[0.16185944 0.05403817 0.917137  ]
 [0.51912486 0.61737616 0.14367746]
 [0.17563682 0.12584817 0.7249324 ]]

**Exercise 8:**

Create the following type of array with random numbers using necessary numpy function.

ee: [[0.15736114 0.64420824 0.58952521 0.59210511 0.42343704 0.09487966]

 [0.61946116 0.87906074 0.74487366 0.87389401 0.23072641 0.22900258]]

In [35]:
#TODO

ee = np.random.random((2,6))

print(ee)

[[0.49453943 0.6458098  0.9456533  0.61691502 0.65264129 0.15595284]
 [0.47428381 0.9195281  0.21429663 0.36428679 0.04060267 0.06952404]]

##Array math

In [36]:
x=np.array([10,20,30,40,50,60])
print(x)

[10 20 30 40 50 60]

In [37]:
#find the maximum element of X
max = np.max(x)
print("max:", max)

max: 60

In [38]:
#mean of values in the X
mean_of_array=np.mean(x)
print("mean:",mean_of_array)

mean: 35.0

In [41]:
# get the 2th power of each value
print("x:",x)
print(np.power(x,3))

x: [10 20 30 40 50 60]
[  1000   8000  27000  64000 125000 216000]

In [42]:
# trigonometric functions 
print(np.sin(x))
print(np.tan(x))

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061  0.32004039]

**Exercise 9:**

x: [[95 90 92]

 [94 96 98]]

max: 98

mean: 94.16666666666667

power: [[9025 8100 8464]

 [8836 9216 9604]]

sin: [[ 0.68326171  0.89399666 -0.77946607]

 [-0.24525199  0.98358775 -0.57338187]]

cos: [[ 0.73017356 -0.44807362 -0.62644445]

 [ 0.96945937 -0.18043045 -0.81928825]]

In [45]:
#TODO

x = np.array([ [95,90,92] , [94,96,98] ])

print(np.max(x))
print(np.mean(x))
print(np.power(x,2))

print(np.sin(x))
print(np.cos(x))

98
94.16666666666667
[[9025 8100 8464]
 [8836 9216 9604]]
[[ 0.68326171  0.89399666 -0.77946607]
 [-0.24525199  0.98358775 -0.57338187]]
[[ 0.73017356 -0.44807362 -0.62644445]
 [ 0.96945937 -0.18043045 -0.81928825]]

# numpy.sum()

The numpy.sum() function is available in the NumPy package of Python. This function is used to compute the sum of all elements, the sum of each row, and the sum of each column of a given array.

In [46]:
import numpy as np  
a=np.array([0.4,0.5])  
b=np.sum(a)  
b

0.9

In [49]:
import numpy as np  
a=np.array([1.4,0.5,0.9,6.1])  
x=np.sum(a, dtype=np.int32)  
x

7

In [50]:
import numpy as np  
a=np.array([[1,4],[3,5]])  
b=np.sum(a)  
b

13

In [51]:
import numpy as np  
a=np.array([[1,4],[3,5]])  
b=np.sum(a,axis=0)  #the sum of the column elements has been calculated accordingly.
b

array([4, 9])

In [52]:
import numpy as np  
a=np.array([[1,4],[3,5]])  
b=np.sum(a,axis=1)  #the sum of the row elements has been calculated accordingly.
print(b)

[5 8]

***Exercise 10:***

Create an array perform various sum operation as shown below.

Array: [[22 23 25]


 [31 32 33]

 
 [34 35 36]]

sum of array: 271


sum of cols: [87 90 94]


sum of rows: [ 70  96 105]

In [55]:
#TODO

arr = np.array([[22,23,25],[31,32,33],[34,35,36]])

print( "total sum" , np.sum(arr))
print( "col sum" , np.sum(arr,axis=0))
print( "row sum" , np.sum(arr,axis=1))

total sum 271
col sum [87 90 94]
row sum [ 70  96 105]

# concatenate()

The concatenate() function is a function from the NumPy package. This function essentially combines NumPy arrays together. This function is basically used for joining two or more arrays of the same shape along a specified axis.

In [57]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

z=np.concatenate((x,y))  

print(z)

[[ 1  2]
 [ 3  4]
 [12 30]]

In [60]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])

print(x)

#Transpose
print(y.T)  

z=np.concatenate((x,y.T), axis=1) 

z

[[1 2]
 [3 4]]
[[12]
 [30]]

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [61]:
import numpy as np  
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

z=np.concatenate((x,y), axis=None)  

z

array([ 1,  2,  3,  4, 12, 30])

**Exercise 11:**

Create an array perform various concatenate operation as shown below.

a: [[1 4 5]]

b: [[22 23 25]

 [31 32 33]

 [34 35 36]]

concatenation1: [[ 1  4  5]

 [22 23 25]

 [31 32 33]

 [34 35 36]]

In [66]:
#TODO

a = np.array([[1 ,4 ,5]])
b = np.array([[22 ,23, 25],[31 ,32, 33],[34, 35, 36]])

z=np.concatenate((a,b))
print(z)

[[ 1  4  5]
 [22 23 25]
 [31 32 33]
 [34 35 36]]

# numpy.append() in Python

In [67]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [68]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)  
c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [69]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=1)  
c

array([[10, 20, 30, 11, 21, 31],
       [40, 50, 60, 42, 52, 62],
       [70, 80, 90, 73, 83, 93]])

**NumPy - Arithmetic Operations**

Functions:add(), subtract(), multiply(), and divide()

In [70]:
x=np.array([[1,1],[1,1]])  
y=np.array([[10,10],[10,10]])
print("x:",x)
print("y:",y)
print("x+y:", np.add(x,y))
print("x-y:", np.subtract(x,y))
print("x*y:", np.multiply(x,y))
print("x/y:", np.divide(x,y))
print("Matrix multiplication of x and y:", np.matmul(x,y))
print("Dot multiplication of x and y:", np.dot(x,y))

x: [[1 1]
 [1 1]]
y: [[10 10]
 [10 10]]
x+y: [[11 11]
 [11 11]]
x-y: [[-9 -9]
 [-9 -9]]
x*y: [[10 10]
 [10 10]]
x/y: [[0.1 0.1]
 [0.1 0.1]]
Matrix multiplication of x and y: [[20 20]
 [20 20]]
Dot multiplication of x and y: [[20 20]
 [20 20]]

**Exercise 12:**

Create an array perform various concatenate operation as shown below.


x: [[ 2 22]

 [22  2]]

y: [[10 10]

 [10 10]]

x*y: [[ 20 220]

 [220  20]]

Matrix multiplication of x and y: [[240 240]

 [240 240]]

Dot multiplication of x and y: [[240 240]

 [240 240]]

In [72]:
#TODO

x = [[2,22],[22,2]]
y = [[10,10],[10,10]]

print("x*y:", np.multiply(x,y))
print()
print("Matrix multiplication of x and y:", np.matmul(x,y))

x*y: [[ 20 220]
 [220  20]]

Matrix multiplication of x and y: [[240 240]
 [240 240]]

How to get run time input for numpy array?

In [73]:
my_array = []
a = int(input("Size of array:"))
for i in range(a):
    my_array.append(int(input("Element:")))
my_array = np.array(my_array)
print(my_array)
print(np.max(my_array))

Size of array:3
Element:1
Element:2
Element:3
[1 2 3]
3